name: Bandit

on:
  push:
    paths:
      - '**/*.py'    # run on any Python file
  pull_request:
    paths:
      - '**/*.py'    # also run on PRs with Python files

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit

      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          args: -r .
